# Pipeline configuration
input_chat_text_path: "../data/01_raw/fart_noises_for_life.txt"
run_loader: False
loaded_chat_parquet_path: "../data/02_loaded/fart_noises_for_life.parquet"
run_cleaner: False
cleaned_chat_parquet_path: "../data/03_cleaned/fart_noises_for_life.parquet"
run_features: False
features_chat_parquet_path: "../data/04_featured/fart_noises_for_life.parquet"
run_model_setup: True
model_input_path: "../data/05_model/fart_noises_for_life_model_input.pkl"
run_model_training: True
trained_model_path: "../data/05_model/fart_noises_for_life_model.pkl"
run_model_prediction: True
